### ISSUE TITLE
Make Helpful buffers behave better

### ISSUE THREAD

**Issue by Townk** [Wilfred/helpful#33]
I have essentially two problems with Helpful:

1. Every time I check a definition using it, Helpful create some persistent buffers (at least 2), one for the searched function source file and one for the Helpful buffer itself.
I think Helpful should use `with-temp-buffer` instead of `find-file` to visit the references (I found this article referencing this trade-off: http://ergoemacs.org/emacs/elisp_find-file_vs_with-temp-buffer.html), this way it wouldn't create a persistent buffer for the source file, and it would be faster.

2. I can't configure Helpful to play nice with Shackle.
This point probably spills over the first one (and that is why I didn't open two issues). Helpful is using `switch-to-buffer` to show its content. Unfortunately, this function does not use the `display-buffer-alist` and is harder to manage the window/buffers it creates. Also, if Helpful would use a function like `display-buffer` instead, it would create a persistent buffer for itself.

**Comment by Wilfred** [comment]
Thanks for reporting!

Your first issue is a bug with elisp-refs. Would you mind opening an issue there?

The second issue has been fixed in #35 :)

**Comment by Townk** [comment]
I'll be more than happy to file a bug on `elisp-refs`, but can you give me a bit more specifics on it? For instance, why calling `find-file` should **not** create a persistent buffer on my Emacs?

If that is the expected behavior, how are you trying to not have the persistent buffer when calling `find'file`?

**Comment by Wilfred** [comment]
OK, I may have misunderstood you. Suppose you look up a function `foo-bar` in a file `foo.el`. Are you saying that:

1. `M-x helpful-function RET foo-bar RET` is also opening `foo.el` in a buffer, or?

2. Pressing RET on a reference in the Helpful buffer is opening `foo.el` in a buffer?

Option 1 would be a bug, whereas 2 is intended behaviour (but all behaviour is open for discussion if it doesn't fit your workflow).

**Comment by Townk** [comment]
What happens is 1

**Comment by naclander** [comment]
@Wilfred this is actually one of the few things that's preventing me moving to `helpful` full time, can you confirm that this is a bug?

**Comment by Wilfred** [comment]
OK, this should now be fixed. Let me know if not.

**Comment by Townk** [comment]
Unfortunately, it's not.

If you open emacs and call `describe-function`, then choose `enable-theme`. Helpful will open 2 buffers:

1. *helpful: enable-theme*
2. custom.el.gz

I just updated emacs and helpful just to be sure and the behavior is still the same.
Also, if I describe anything else, hepful will keep one buffer for each "help" I get. I understand that some people might find that useful, but wouldn't be possible to have a flag to make it behave just like plain old `help` (one buffer for all help messages you can get)?

**Comment by Wilfred** [comment]
Sure, I understand creating multiple helpful buffers may not be to everyone's taste :). Would you mind creating a separate issue?

**Comment by Townk** [comment]
Sure, just ask as a question. Some project have an adamant opinion about features. Just wanted to get the feel :)

**Comment by Wilfred** [comment]
Are you sure you'd upgraded? I've added a test too, to confirm this bug is fixed.
