### ISSUE TITLE
helpful seems to break recentf

### ISSUE THREAD

**Issue by wbolster** [Wilfred/helpful#74]
i see errors upon emacs startup when enabling `(recentf-mode)`:

```
Invalid read syntax: "#"
```

the `recentf-save.el` file contains items that look like the one with the `#` below:

``` emacs
(setq recentf-list
      '(
        "/home/wbolster/Configuration/Emacs/init.el"
        #("/usr/share/emacs/25.3.50/lisp/recentf.el.gz" 0 43 (button (t) category helpful-navigate-button-button path #0 position 2983))
        "other files here"
        ))
```

...which leads me to think that `helpful` might be (part of) the problem here.

when i delete the offending lines and restart emacs, startup succeeds as usual.

however, after i show a `helpful` buffer for a function and click the file name to open the source file, the offending line again makes it into `recentf-save.el` upon shutdown, and causes an error on next startup.

help appreciated. :)

**Comment by Wilfred** [comment]
I think this was fixed in #68 -- could you confirm you're using the latest version?

**Comment by wbolster** [comment]
oh oops, i didn't spot that one.

i checked my local install, and it already has the `helpful--no-properties` `defun`, so it seems that fix is already included in my local version, yet i still encounter this problem somehow. 😕 

any reason you use this helper instead of using the 1-arg `(substring-no-properties foo)` form?

**Comment by wbolster** [comment]
ah, i see 3698c95359fa45b38f65f08bfa350996f1e91af8 already addressed that

**Comment by wbolster** [comment]
with the latest melpa version i still get lines like this in `recentf-save.el`:

```
        #("/usr/share/emacs/25.3.50/lisp/frame.el.gz" 0 41 (button (t) category helpful-navigate-button-button path #0 position 2815))
```

even though `helpful.el` contains `(substring-no-properties ...)` in `(helpful--navigate)`.

**Comment by Wilfred** [comment]
I'm not able to replicate this. Emacs is very stateful: can you confirm that you still get this, and it's not an old value of `recentf-list` or using an old value from `~/.recentf`?

If you can reproduce this, please let me know how :)

**Comment by wbolster** [comment]
i can confirm that this problem still occurs, across many emacs restarts, with me manulaly getting rid of the offending lines in `recentf-save.el` (using another editor) in the mean time.

it seems intermittent (happens sometimes), and i have no clear steps to reproduce, unfortunately.

perhaps it depends on which helpful button i use?

any ideas on how to (help) debug this?

**Comment by Wilfred** [comment]
Thanks for confirming. Try adding this to your configuration:

```emacs-lisp
(defadvice find-file (before wh/find-file-check-properties activate)
  "Throw an error if we're called with a propertized string."
  (let ((path (ad-get-arg 0)))
    (when (get-text-property 0 'button path)
      (error "Calling find-file with a propertized path"))))
```

This will throw an error if any code calls `find-file` with a string with a button property. Please paste the traceback you get (use `toggle-debug-on-error`).

**Comment by Wilfred** [comment]
Thanks for your help with this. I think this should be fixed properly, please see the changelog for notes about cleaning up any files written by recentf.

**Comment by wbolster** [comment]
awesome, i tried debugging this as you suggested but didn't get any results. i also tried this:

```
(defun w--check-propertized-buffer-name ()
  (let ((path (buffer-file-name)))
    (message "path %S" path)
    (when path
      (unless (equal-including-properties path (substring-no-properties path))
        (error "weird file path %S" path)
        (backtrace)
        (debug)))))
(add-hook 'find-file-hook #'w--check-propertized-buffer-name)
```

again without luck.

awesome that you seem to have found the root cause! thanks!
